# Generated by Django 4.2.16 on 2026-04-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialrecord',
            new_name='financial_r_type_346f26_idx',
            old_name='financial_r_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='financialrecord',
            new_name='financial_r_categor_2871f2_idx',
            old_name='financial_r_category_idx',
        ),
        migrations.RenameIndex(
            model_name='financialrecord',
            new_name='financial_r_is_dele_213f2d_idx',
            old_name='financial_r_is_deleted_idx',
        ),
    ]
